MAJOR_VERSION=0
MINOR_VERSION=6
REVISION=0
SO_VERSION=$(MAJOR_VERSION).$(MINOR_VERSION)

prefix?=/usr
exec_prefix?=/usr
bindir?=$(exec_prefix)/bin
libdir?=$(prefix)/lib
plugindir?=$(libdir)
includedir?=$(prefix)/include

SHELL=/bin/bash
PKG_CONFIG?=pkg-config
INSTALL?=install
